/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.sql.*;
import javax.swing.JOptionPane;
import conexion.ConexionBD;

//public class Acceso extends javax.swing.JFrame{
  //  ConexionBD conBD = new ConexionBD();



/**
 *
 * @author ivis3
 */
public class Acceso extends javax.swing.JFrame {

    ConexionBD conBD = new ConexionBD();

            
            
    public Acceso() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        lblTituloLogin = new javax.swing.JLabel();
        panAcceso = new javax.swing.JPanel();
        txtUsuarioAcceso = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblUsuarioAcceso = new javax.swing.JLabel();
        lblPasswordAcceso = new javax.swing.JLabel();
        txtPasswordAcceso = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblLogoAcceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Control Acceso Ayala");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panFondo.setPreferredSize(new java.awt.Dimension(565, 715));

        lblTituloLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTituloLogin.setForeground(new java.awt.Color(100, 99, 97));
        lblTituloLogin.setText("ACCESO SISTEMA");

        panAcceso.setBackground(new java.awt.Color(217, 143, 149));
        panAcceso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 99, 97), 2, true));
        panAcceso.setForeground(new java.awt.Color(217, 143, 149));

        txtUsuarioAcceso.setBackground(new java.awt.Color(217, 143, 149));
        txtUsuarioAcceso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtUsuarioAcceso.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioAcceso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUsuarioAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioAccesoActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(49, 45, 45));
        jSeparator2.setForeground(new java.awt.Color(49, 45, 45));

        lblUsuarioAcceso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuarioAcceso.setForeground(new java.awt.Color(49, 45, 45));
        lblUsuarioAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-acceso-48.png"))); // NOI18N
        lblUsuarioAcceso.setText("   Usuario:");

        lblPasswordAcceso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPasswordAcceso.setForeground(new java.awt.Color(49, 45, 45));
        lblPasswordAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-llave-2-48.png"))); // NOI18N
        lblPasswordAcceso.setText("Password:");

        txtPasswordAcceso.setBackground(new java.awt.Color(217, 143, 149));
        txtPasswordAcceso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPasswordAcceso.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordAcceso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jSeparator1.setBackground(new java.awt.Color(49, 45, 45));
        jSeparator1.setForeground(new java.awt.Color(49, 45, 45));

        btnIngresar.setBackground(new java.awt.Color(182, 145, 152));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(247, 244, 244));
        btnIngresar.setText("Ingresar a sistema");
        btnIngresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(182, 145, 152));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(247, 244, 244));
        btnBorrar.setText("Borrar datos");
        btnBorrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAccesoLayout = new javax.swing.GroupLayout(panAcceso);
        panAcceso.setLayout(panAccesoLayout);
        panAccesoLayout.setHorizontalGroup(
            panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccesoLayout.createSequentialGroup()
                .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAccesoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuarioAcceso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordAcceso, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panAccesoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPasswordAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panAccesoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtUsuarioAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panAccesoLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panAccesoLayout.setVerticalGroup(
            panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccesoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioAcceso)
                    .addComponent(txtUsuarioAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordAcceso)
                    .addComponent(txtPasswordAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        lblLogoAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoBoutique200px.png"))); // NOI18N

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                        .addComponent(lblTituloLogin)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                        .addComponent(lblLogoAcceso)
                        .addGap(179, 179, 179))))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTituloLogin)
                .addGap(30, 30, 30)
                .addComponent(lblLogoAcceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        panAcceso.getAccessibleContext().setAccessibleName("Acceso al sistema");

        getContentPane().add(panFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtUsuarioAcceso.setText(null);
        txtPasswordAcceso.setText(null);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        try{
            String usuario = txtUsuarioAcceso.getText();
            String pass = txtPasswordAcceso.getText();
            boolean error = true;
            conBD.conectarBase();
            conBD.rs = conBD.stmt.executeQuery("select * from usuario");
            while (conBD.rs.next() == true){
                if (usuario.equals(conBD.rs.getString("usuario")) && pass.equals(conBD.rs.getString("pass"))){
                    error = false;
                    SistemaVentas accesoSistema = new SistemaVentas();//llamada a interface

                    JOptionPane.showMessageDialog(null, "Bienvenido a Sistema\n Usuario Administrador :\n\n" + usuario );
                    accesoSistema.setVisible(true);//muestra ventana
                    this.hide();//oculta ventana anterior
                }
            }
            if (error == true){
                JOptionPane.showMessageDialog(null, "Error al ingresar datos.\n Verifique");
                this.txtUsuarioAcceso.setText(null);
                this.txtPasswordAcceso.setText(null);
                this.txtUsuarioAcceso.requestFocus();//pocisiona cursor a caja usuario
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Error de BD Validacion: \n\n"+ ex);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAccesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblLogoAcceso;
    private javax.swing.JLabel lblPasswordAcceso;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JLabel lblUsuarioAcceso;
    private javax.swing.JPanel panAcceso;
    private javax.swing.JPanel panFondo;
    private javax.swing.JPasswordField txtPasswordAcceso;
    private javax.swing.JTextField txtUsuarioAcceso;
    // End of variables declaration//GEN-END:variables
}
